version: '3.7'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/fiappi
      - SPRING_DATASOURCE_USERNAME=fiappi
      - SPRING_DATASOURCE_PASSWORD=fiappi
      - API_SECURITY_SERVER_URL=http://app:8080
      - API_SECURITY_TOKEN_SECRET=my-secret-key
    networks:
      - springboot-postgres-network
volumes:
  postgres-data:
networks:
  springboot-postgres-network:
    external: true

